const actionTypes = {
  SET_PRODUCTS_REQUEST: 'SET_PRODUCTS_REQUEST',
  SET_PRODUCTS_RECEIVE: 'SET_PRODUCTS_RECEIVE',
  SET_PRODUCTS_FAIL: 'SET_PRODUCTS_FAIL',
  SELECTED_PRODUCT: 'SELECTED_PRODUCT',
  REMOVE_SELECTED_PRODUCT: 'REMOVE_SELECTED_PRODUCT',
  SET_LOADING_ACTION: 'SET_LOADING_ACTION',
  SET_PRODUCT_FAIL: 'SET_PRODUCT_FAIL',
}

export default actionTypes
