const actionTypes = {
  SET_PRODUCTS_REQUEST: 'SET_PRODUCTS_REQUEST',
  SET_PRODUCTS_RECEIVE: 'SET_PRODUCTS_RECEIVE',
  SET_PRODUCTS_FAIL: 'SET_PRODUCTS_FAIL',

  PRODUCT_DETAILS_REQUEST: 'PRODUCT_DETAILS_REQUEST',
  PRODUCT_DETAILS_RECEIVE: 'PRODUCT_DETAILS_RECEIVE',
  PRODUCT_DETAILS_FAIL: 'PRODUCT_DETAILS_FAIL',

  REMOVE_SELECTED_PRODUCT: 'REMOVE_SELECTED_PRODUCT',
  SET_LOADING_ACTION: 'SET_LOADING_ACTION',
}

export default actionTypes
