const actionTypes = {
  PRODUCT_DETAILS_REQUEST: 'PRODUCT_DETAILS_REQUEST',
  PRODUCT_DETAILS_RECEIVE: 'PRODUCT_DETAILS_RECEIVE',
  PRODUCT_DETAILS_FAIL: 'PRODUCT_DETAILS_FAIL',
  SET_LOADING_ACTION: 'SET_LOADING_ACTION',
}

export default actionTypes
