const actionTypes = {
  SET_PRODUCTS_REQUEST: 'SET_PRODUCTS_REQUEST',
  SET_PRODUCTS_RECEIVE: 'SET_PRODUCTS_RECEIVE',
  SET_PRODUCTS_FAIL: 'SET_PRODUCTS_FAIL',
  SET_LOADING_ACTION: 'SET_LOADING_ACTION',
  DELETE_PRODUCT: 'DELETE_PRODUCT',
}

export default actionTypes
